language: php

matrix:
  fast_finish: true
  include:
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

#after_script:
#  - vendor/bin/test-reporter

#addons:
#  code_climate:
#    repo_token: $CODE_CLIMATE_TOKEN
